
export const careerData = [
  {
    "job": "Machine Learning Engineer",
    "requiredSkills": [
      "Python",
      "Scikit-learn",
      "TensorFlow",
      "PyTorch",
      "ML Ops",
      "Model Deployment",
      "Feature Engineering",
      "Data Preprocessing",
      "Cloud Platforms (AWS/GCP/Azure)",
      "Model Monitoring"
    ]
  },
  {
    "job": "Generative AI Engineer",
    "requiredSkills": [
      "Prompt Engineering",
      "LLM Development (OpenAI",
      "LLaMA",
      "Falcon)",
      "Fine-tuning",
      "LangChain",
      "Vector Databases",
      "AI Ethics",
      "RAG Pipelines",
      "API Integration"
    ]
  },
  {
    job: 'Product Manager',
    requiredSkills: [
      "Product Strategy",
      "Roadmap Planning",
      "Market Research",
      "UX/UI Understanding",
      "Agile/Scrum",
      "Stakeholder Management",
      "Data Analysis (Excel",
      "SQL",
      "Python optional)",
      "Communication",
      "Prioritization",
      "Problem Solving",
    ],
  },
  {
    job: 'Blockchain Developer',
    requiredSkills: [
      'Solidity',
      'Ethereum',
      'Smart Contracts',
      'Web3.js',
      'Cryptography',
      'dApps Development',
      'Security',
      'Layer 2 Scaling Solutions',
    ],
  },
  {
    job: 'AR/VR Developer',
    requiredSkills: [
      'Unity',
      'Unreal Engine',
      'C#',
      '3D Modeling',
      'ARKit',
      'ARCore',
      'OpenXR',
      'Spatial Computing',
      'XR Optimization',
    ],
  },
  {
    job: 'IoT Engineer',
    requiredSkills: [
      'C/C++',
      'MQTT',
      'Edge Computing',
      'Sensor Data Processing',
      'Security',
      'Embedded Systems',
      'Real-time Analytics',
    ],
  },
  {
    job: 'Quantum Computing Researcher',
    requiredSkills: [
      'Qiskit',
      'Cirq',
      'Quantum Algorithms',
      'Linear Algebra',
      'Quantum Error Correction',
      'Python',
    ],
  },
  {
    job: 'Database Administrator',
    requiredSkills: [
      "SQL",
      "MySQL",
      "PostgreSQL",
      "Oracle",
      "MongoDB",
      "NoSQL",
      "Database Design",
      "Normalization",
      "Query Optimization",
      "Backup & Recovery",
      "Replication",
      "Security",
      "Indexing",
      "Stored Procedures",
      "PL/SQL",
      "Cloud Databases (RDS",
      "CosmosDB",
      "BigQuery)",
      "Monitoring",
      "Communication"
    ],
  },
  {
    job: 'System Administrator',
    requiredSkills: [
      "Linux",
      "Windows Server",
      "Active Directory",
      "Networking",
      "Firewalls",
      "Virtualization (VMware",
      "Hyper-V)",
      "Backup & Recovery",
      "Monitoring",
      "Troubleshooting",
      "Bash",
      "PowerShell",
      "User Management",
      "Security",
      "Patching",
      "Documentation",
      "Communication"
    ],
  },
  {
    job: 'IT Support Specialist',
    requiredSkills: [
      "Troubleshooting",
      "Hardware",
      "Software",
      "Networking",
      "Windows",
      "Linux",
      "MacOS",
      "Active Directory",
      "Ticketing Systems",
      "Remote Support",
      "Communication",
      "Documentation",
      "Customer Service",
      "Problem Solving",
      "Time Management"
    ],
  },
  {
    job: 'Graphic Designer',
    requiredSkills: [
      'Adobe Creative Suite (Photoshop',
      'Illustrator',
      'InDesign)',
      'Typography',
      'Color Theory',
      'Branding',
      'Layout Design',
      'Digital Design',
      'Print Design',
      'UI/UX Basics',
      'Creativity',
      'Client Communication',
      'Portfolio Development',
    ],
  },
  {
    job: 'Web Designer',
    requiredSkills: [
      'HTML',
      'CSS',
      'JavaScript',
      'Adobe Creative Suite',
      'Figma',
      'Sketch',
      'Responsive Design',
      'UI/UX Design',
      'Wireframing',
      'Prototyping',
      'Cross-browser Compatibility',
      'SEO Basics',
      'User Research',
    ],
  },
  {
    job: 'UX/UI Designer',
    requiredSkills: [
      "UI Design",
      "UX Design",
      "Wireframing",
      "Prototyping",
      "Figma",
      "Adobe XD",
      "Sketch",
      "InVision",
      "Design Systems",
      "Usability Testing",
      "Human-Computer Interaction",
      "Accessibility",
      "Responsive Design",
      "HTML",
      "CSS",
      "Collaboration",
      "Creativity",
      "Communication"
    ],
  },
  {
    "job": "Process Engineer",
    "requiredSkills": [
      "Process Design",
      "Process Simulation (Aspen Plus",
      "HYSYS",
      "CHEMCAD)",
      "Heat Transfer",
      "Mass Transfer",
      "Fluid Dynamics",
      "Thermodynamics",
      "Process Control",
      "P&ID",
      "Chemical Reaction Engineering",
      "Optimization",
      "Equipment Design",
      "Safety Standards (HAZOP",
      "PHA)",
      "Troubleshooting",
      "Data Analysis",
      "Project Management",
      "Communication"
    ]
  },
  {
    "job": "Chemical Engineer (General)",
    "requiredSkills": [
      "Thermodynamics",
      "Heat & Mass Transfer",
      "Fluid Mechanics",
      "Chemical Kinetics",
      "Process Simulation",
      "Aspen Plus",
      "MATLAB",
      "Process Safety",
      "Equipment Design",
      "Process Control",
      "Environmental Engineering",
      "Materials Science",
      "Project Management",
      "Problem Solving"
    ]
  },
  {
    "job": "Petroleum Engineer",
    "requiredSkills": [
      "Reservoir Engineering",
      "Drilling Engineering",
      "Production Engineering",
      "Well Testing",
      "Fluid Flow in Porous Media",
      "EOR (Enhanced Oil Recovery)",
      "Simulation Tools (Eclipse",
      "CMG)",
      "Petrel",
      "Petroleum Geology",
      "Safety & Regulations",
      "Project Management",
      "Data Analysis",
      "Communication"
    ]
  },
  {
    "job": "Environmental Engineer",
    "requiredSkills": [
      "Wastewater Treatment",
      "Air Pollution Control",
      "Solid Waste Management",
      "Environmental Impact Assessment",
      "Environmental Laws & Regulations",
      "Sustainability",
      "Life Cycle Assessment (LCA)",
      "Renewable Energy",
      "Simulation Tools",
      "Data Analysis",
      "GIS",
      "Problem Solving",
      "Communication"
    ]
  },
  {
    "job": "Materials Engineer",
    "requiredSkills": [
      "Materials Science",
      "Polymers",
      "Ceramics",
      "Nanomaterials",
      "Metallurgy",
      "Composites",
      "Characterization Techniques (SEM",
      "TEM",
      "XRD)",
      "Failure Analysis",
      "Corrosion Engineering",
      "Coatings",
      "Process Engineering",
      "R&D",
      "Testing",
      "Documentation",
      "Communication"
    ]
  },
  {
    "job": "Pharmaceutical Engineer",
    "requiredSkills": [
      "Bioprocess Engineering",
      "GMP (Good Manufacturing Practice)",
      "Process Validation",
      "Cleanroom Technology",
      "Fermentation Technology",
      "Downstream Processing",
      "Drug Formulation",
      "Biochemistry",
      "Microbiology",
      "Chromatography",
      "Process Simulation",
      "Regulatory Compliance (FDA",
      "EMA)",
      "Data Analysis",
      "Communication"
    ]
  },
  {
    "job": "Biochemical Engineer",
    "requiredSkills": [
      "Bioprocess Design",
      "Enzyme Technology",
      "Fermentation",
      "Metabolic Engineering",
      "Synthetic Biology",
      "Downstream Processing",
      "Cell Culture",
      "Bioreactors",
      "Biochemistry",
      "Molecular Biology",
      "Process Simulation",
      "Biotechnology Tools",
      "Data Analysis",
      "Communication"
    ]
  },
  {
    "job": "R&D Chemical Engineer",
    "requiredSkills": [
      "Chemical Synthesis",
      "Catalysis",
      "Process Development",
      "Lab Techniques",
      "Process Optimization",
      "Simulation Tools",
      "Materials Development",
      "Experimentation",
      "Data Analysis",
      "Technical Writing",
      "Creativity",
      "Project Management",
      "Collaboration"
    ]
  },
  {
    "job": "Plant / Production Engineer (Chemical)",
    "requiredSkills": [
      "Plant Operations",
      "Unit Operations",
      "Process Control",
      "DCS/SCADA Systems",
      "Troubleshooting",
      "Safety Standards",
      "Maintenance",
      "Process Optimization",
      "Lean Manufacturing",
      "Six Sigma",
      "Teamwork",
      "Communication",
      "Project Management"
    ]
  },
  {
    "job": "Safety Engineer (Chemical Domain)",
    "requiredSkills": [
      "Process Safety",
      "HAZOP",
      "PHA",
      "Risk Assessment",
      "Fire & Explosion Analysis",
      "Safety Standards (OSHA",
      "NFPA",
      "ISO)",
      "Hazardous Material Handling",
      "Environmental Health & Safety (EHS)",
      "Safety Instrumented Systems",
      "Emergency Planning",
      "Auditing",
      "Communication"
    ]
  },
  {
    "job": "Food Process Engineer",
    "requiredSkills": [
      "Food Chemistry",
      "Food Microbiology",
      "Process Engineering",
      "Heat & Mass Transfer",
      "Drying",
      "Freezing",
      "Pasteurization",
      "Food Safety (HACCP",
      "GMP)",
      "Bioprocessing",
      "Packaging Technology",
      "Quality Assurance",
      "Data Analysis",
      "Communication"
    ]
  },
  {
    "job": "Energy Engineer (Chemical Domain)",
    "requiredSkills": [
      "Renewable Energy",
      "Fuel Cells",
      "Biofuels",
      "Energy Storage",
      "Heat & Mass Transfer",
      "Thermodynamics",
      "Process Simulation",
      "Energy Efficiency",
      "Life Cycle Assessment",
      "Sustainability",
      "Project Management",
      "Data Analysis",
      "Communication"
    ]
  },
  {
    "job": "Electrical Engineer",
    "requiredSkills": [
      "Circuit Design",
      "Power Systems",
      "Control Systems",
      "Signal Processing",
      "Embedded Systems",
      "MATLAB",
      "Simulink",
      "PCB Design",
      "VLSI",
      "Renewable Energy",
      "Electrical Machines",
      "Power Electronics",
      "SCADA",
      "PLC",
      "IoT",
      "Communication"
    ]
  },
  {
    "job": "Electronics Engineer",
    "requiredSkills": [
      "Analog Electronics",
      "Digital Electronics",
      "Circuit Design",
      "Microcontrollers",
      "FPGA",
      "VHDL",
      "Verilog",
      "Embedded Systems",
      "IoT",
      "Signal Processing",
      "PCB Design",
      "MATLAB",
      "Troubleshooting"
    ]
  },
  {
    "job": "Power Engineer",
    "requiredSkills": [
      "Power Systems",
      "Grid Management",
      "Renewable Energy",
      "Transmission & Distribution",
      "Power Electronics",
      "HVDC",
      "Protection Systems",
      "Smart Grid",
      "SCADA",
      "MATLAB",
      "Communication"
    ]
  },
  {
    "job": "Instrumentation Engineer",
    "requiredSkills": [
      "Sensors",
      "Instrument Calibration",
      "Process Control",
      "PLC",
      "SCADA",
      "Control Systems",
      "Data Acquisition",
      "Troubleshooting",
      "Automation",
      "MATLAB",
      "Simulink"
    ]
  },
  {
    "job": "Civil Engineer",
    "requiredSkills": [
      "Structural Analysis",
      "RCC Design",
      "AutoCAD",
      "STAAD Pro",
      "ETABS",
      "Surveying",
      "Construction Management",
      "Estimation",
      "Building Codes",
      "Geotechnical Engineering",
      "Transportation Engineering",
      "Environmental Engineering",
      "Project Management"
    ]
  },
  {
    "job": "Structural Engineer",
    "requiredSkills": [
      "Finite Element Analysis",
      "Structural Design",
      "RCC",
      "Steel Structures",
      "Earthquake Engineering",
      "AutoCAD",
      "STAAD Pro",
      "ETABS",
      "Safety Codes",
      "Project Management"
    ]
  },
  {
    "job": "Geotechnical Engineer",
    "requiredSkills": [
      "Soil Mechanics",
      "Foundation Design",
      "Site Investigation",
      "Slope Stability",
      "Retaining Walls",
      "Geo-environmental Engineering",
      "AutoCAD",
      "Safety Standards"
    ]
  },
  {
    "job": "Transportation Engineer",
    "requiredSkills": [
      "Traffic Engineering",
      "Highway Design",
      "Pavement Design",
      "Transportation Planning",
      "GIS",
      "AutoCAD",
      "Civil 3D",
      "Project Management"
    ]
  },
  {
    "job": "Biomedical Engineer",
    "requiredSkills": [
      "Medical Imaging",
      "Signal Processing",
      "Biomechanics",
      "Biomaterials",
      "Tissue Engineering",
      "Medical Devices",
      "Regulatory Standards (FDA",
      "ISO)",
      "MATLAB",
      "Python",
      "Lab Skills",
      "3D Printing",
      "Prosthetics",
      "Data Analysis"
    ]
  },
  {
    "job": "Clinical Engineer",
    "requiredSkills": [
      "Medical Device Maintenance",
      "Calibration",
      "Hospital Equipment",
      "Safety Standards",
      "Healthcare Regulations",
      "Troubleshooting",
      "Biomedical Instrumentation"
    ]
  },
  {
    "job": "Rehabilitation Engineer",
    "requiredSkills": [
      "Prosthetics",
      "Orthotics",
      "Assistive Technology",
      "Human Factors",
      "Biomechanics",
      "CAD",
      "3D Printing",
      "Materials Science"
    ]
  },
  {
    "job": "Aerospace Engineer",
    "requiredSkills": [
      "Aerodynamics",
      "Propulsion",
      "Flight Mechanics",
      "Avionics",
      "Structural Analysis",
      "CAD (CATIA",
      "SolidWorks)",
      "CFD",
      "MATLAB",
      "Control Systems",
      "Orbital Mechanics",
      "Simulation"
    ]
  },
  {
    "job": "Avionics Engineer",
    "requiredSkills": [
      "Embedded Systems",
      "Control Systems",
      "Navigation Systems",
      "Communication",
      "FPGA",
      "VHDL",
      "Troubleshooting",
      "Safety Standards"
    ]
  },
  {
    "job": "Aircraft Design Engineer",
    "requiredSkills": [
      "Aerodynamics",
      "Structural Analysis",
      "CAD (CATIA",
      "NX",
      "SolidWorks)",
      "Composite Materials",
      "Propulsion Systems",
      "Manufacturing Processes",
      "Testing"
    ]
  },
  {
    "job": "Space Systems Engineer",
    "requiredSkills": [
      "Satellite Design",
      "Orbital Mechanics",
      "Spacecraft Dynamics",
      "Control Systems",
      "Systems Engineering",
      "Simulation Tools",
      "Project Management"
    ]
  },
  {
    "job": "Industrial Engineer",
    "requiredSkills": [
      "Operations Research",
      "Supply Chain Management",
      "Lean Manufacturing",
      "Six Sigma",
      "Process Optimization",
      "Simulation Tools (Arena",
      "FlexSim)",
      "Project Management",
      "Quality Control",
      "Data Analysis",
      "Ergonomics"
    ]
  },
  {
    "job": "Quality Engineer",
    "requiredSkills": [
      "Quality Assurance",
      "ISO Standards",
      "Six Sigma",
      "Lean",
      "Statistical Process Control",
      "Root Cause Analysis",
      "Documentation",
      "Auditing"
    ]
  },
  {
    "job": "Manufacturing Engineer",
    "requiredSkills": [
      "CNC",
      "CAD/CAM",
      "Production Planning",
      "Lean Manufacturing",
      "Six Sigma",
      "Robotics",
      "PLC",
      "Process Optimization",
      "Troubleshooting"
    ]
  },
  {
    "job": "Marine Engineer",
    "requiredSkills": [
      "Naval Architecture",
      "Ship Design",
      "Propulsion Systems",
      "Fluid Mechanics",
      "Thermodynamics",
      "CAD",
      "CFD",
      "Safety Regulations (IMO",
      "SOLAS)",
      "Maintenance",
      "Troubleshooting"
    ]
  },
  {
    "job": "Naval Architect",
    "requiredSkills": [
      "Ship Stability",
      "Structural Design",
      "Marine Hydrodynamics",
      "CAD",
      "CFD",
      "Materials Science",
      "Safety Standards",
      "Project Management"
    ]
  },
  {
    "job": "Offshore Engineer",
    "requiredSkills": [
      "Offshore Structures",
      "Oil & Gas Platforms",
      "Subsea Systems",
      "Fluid Mechanics",
      "Structural Analysis",
      "Safety Standards",
      "CAD",
      "Project Management"
    ]
  },
  {
    "job": "Mechanical Design Engineer",
    "requiredSkills": [
      "CAD",
      "3D Modeling",
      "CAE",
      "FEA",
      "Optimization",
      "GD&T",
      "Tolerance Analysis",
      "Material Science",
      "Simulation",
      "Computational Fluid Dynamics",
      "Prototyping",
      "Technical Drawing",
      "Documentation",
      "Version Control",
      "PLM",
      "Creativity",
      "Communication",
      "Attention to Detail",
      "Project Management"
    ]
  },
  {
    "job": "Production / Process Engineer",
    "requiredSkills": [
      "Manufacturing Processes",
      "CNC Machining",
      "Lean Manufacturing",
      "Six Sigma",
      "Process Optimization",
      "Tool Design",
      "Jigs & Fixtures",
      "Automation",
      "PLC",
      "SCADA",
      "Robotics",
      "Quality Control",
      "Statistical Process Control",
      "Cost Estimation",
      "Root Cause Analysis",
      "Maintenance Knowledge",
      "Communication",
      "Teamwork"
    ]
  },
  {
    "job": "Quality Engineer / Assurance",
    "requiredSkills": [
      "Quality Assurance",
      "Statistical Process Control",
      "ISO Standards",
      "Auditing",
      "Statistical Methods",
      "GD&T",
      "Metrology",
      "Root Cause Analysis",
      "Testing",
      "Validation",
      "Documentation",
      "Communication",
      "Attention to Detail",
      "Regulatory Compliance"
    ]
  },
  {
    "job": "Maintenance / Reliability Engineer",
    "requiredSkills": [
      "Preventive Maintenance",
      "Predictive Maintenance",
      "Vibration Analysis",
      "Thermography",
      "Reliability Engineering",
      "Root Cause Analysis",
      "PLC",
      "SCADA",
      "Automation Systems",
      "Sensors",
      "IoT",
      "Data Analytics",
      "Field Commissioning",
      "Troubleshooting",
      "Documentation",
      "System Integration",
      "Safety Standards"
    ]
  },
  {
    "job": "HVAC / Thermal Systems Engineer",
    "requiredSkills": [
      "Heat Transfer",
      "Thermodynamics",
      "Fluid Mechanics",
      "Thermal Analysis",
      "Heat Exchangers",
      "CFD",
      "Thermal Systems Design",
      "HVAC Design",
      "Energy Efficiency",
      "Ducting",
      "Refrigeration Cycles",
      "Simulation Tools",
      "Controls",
      "Sustainability",
      "Communication"
    ]
  },
  {
    "job": "Automotive Engineer",
    "requiredSkills": [
      "Vehicle Dynamics",
      "Powertrain Systems",
      "Engines",
      "Control Systems",
      "CAD",
      "CAE",
      "FEA",
      "Dynamics",
      "Vibrations",
      "Materials",
      "CFD",
      "Aerodynamics",
      "Embedded Systems",
      "Sensors",
      "Testing",
      "Validation",
      "Manufacturing Processes",
      "Project Management"
    ]
  },
  {
    "job": "Manufacturing / Automation Engineer",
    "requiredSkills": [
      "Automation",
      "PLC",
      "SCADA",
      "Robotics",
      "CNC Machining",
      "Additive Manufacturing",
      "Process Planning",
      "Lean",
      "Six Sigma",
      "IoT Integration",
      "Control Systems",
      "Systems Engineering",
      "Tooling",
      "Supply Chain",
      "Communication",
      "Project Management"
    ]
  },
  {
    "job": "Thermal / Heat Transfer Engineer",
    "requiredSkills": [
      "Heat Transfer",
      "Thermal Analysis",
      "Convection",
      "Conduction",
      "Radiation",
      "CFD",
      "Material Science",
      "Thermodynamics",
      "Simulation",
      "Heat Exchangers",
      "Cooling Systems",
      "Energy Systems",
      "Optimization",
      "Documentation",
      "Communication"
    ]
  },
  {
    "job": "Aerospace / Aerostructure Engineer",
    "requiredSkills": [
      "Aerodynamics",
      "Structural Analysis",
      "FEA",
      "Composite Materials",
      "Stress Analysis",
      "CFD",
      "Control Systems",
      "Dynamics",
      "Vibration",
      "Material Science",
      "CAD",
      "CAE",
      "System Integration",
      "Testing",
      "Safety Standards",
      "Certification"
    ]
  },
  {
    "job": "Mechatronics / Robotics Engineer",
    "requiredSkills": [
      "Robotics",
      "Control Systems",
      "Sensors",
      "Actuators",
      "Embedded Systems",
      "CAD",
      "Simulation",
      "Automation",
      "Kinematics",
      "Dynamics",
      "System Integration",
      "IoT",
      "Programming",
      "Python",
      "C++",
      "Machine Vision",
      "Communication"
    ]
  },
  {
    "job": "R&D / Innovation Engineer",
    "requiredSkills": [
      "Simulation",
      "Prototyping",
      "Materials Testing",
      "CAD",
      "CAE",
      "FEA",
      "CFD",
      "Experimentation",
      "Data Analytics",
      "Machine Learning",
      "Generative Design",
      "Innovation",
      "Creativity",
      "Documentation",
      "Project Management",
      "Cross-functional Communication"
    ]
  },
  {
    "job": "Structural / Stress Analyst",
    "requiredSkills": [
      "FEA",
      "Solid Mechanics",
      "Stress Analysis",
      "Strain Analysis",
      "Material Properties",
      "Simulation",
      "CAD",
      "Fatigue Analysis",
      "Creep Analysis",
      "Optimization",
      "Documentation",
      "Communication"
    ]
  },
  {
    "job": "Tooling / Dies / Fixture Design Engineer",
    "requiredSkills": [
      "Tool Design",
      "Die Design",
      "Jigs",
      "Fixtures",
      "GD&T",
      "CAD",
      "CAM",
      "Manufacturing Processes",
      "CNC Programming",
      "Material Knowledge",
      "Tolerance Analysis",
      "Documentation",
      "Communication"
    ]
  },
  {
    "job": "Project Engineer (Mechanical)",
    "requiredSkills": [
      "Project Management",
      "Scheduling",
      "Cost Estimation",
      "Resource Allocation",
      "Risk Management",
      "Communication",
      "Vendor Management",
      "Technical Understanding",
      "CAD",
      "Simulation",
      "Integration",
      "Decision Making"
    ]
  },
  {
    "job": "Field / Commissioning Engineer",
    "requiredSkills": [
      "Installation",
      "Commissioning",
      "Field Testing",
      "Troubleshooting",
      "PLC",
      "SCADA",
      "Sensors",
      "Instrumentation",
      "System Integration",
      "Documentation",
      "Safety Standards",
      "Communication",
      "Project Execution"
    ]
  },
  {
    "job": "Energy / Power Systems Engineer",
    "requiredSkills": [
      "Thermodynamics",
      "Heat Transfer",
      "Power Cycles",
      "Turbomachinery",
      "CFD",
      "Fluid Systems",
      "Energy Systems",
      "Simulation",
      "Materials",
      "Control Systems",
      "Sustainability",
      "Testing",
      "Validation"
    ]
  }
  ,

  {
    job: 'Digital Artist',
    requiredSkills: [
      'Digital Painting',
      'Adobe Creative Suite',
      'Procreate',
      'Concept Art',
      '3D Modeling (Blender/Maya)',
      'Texture Painting',
      'Character Design',
      'Environment Design',
      'Art Fundamentals',
      'Portfolio Development',
    ],
  },
  {
    job: '3D Artist/Animator',
    requiredSkills: [
      'Maya',
      'Blender',
      '3ds Max',
      'ZBrush',
      'Substance Painter',
      'Rigging',
      'Animation Principles',
      'Lighting',
      'Rendering',
      'Texturing',
      'Sculpting',
      'Motion Graphics',
      'Storytelling',
    ],
  },
  {
    job: 'Video Editor',
    requiredSkills: [
      'Adobe Premiere Pro',
      'Final Cut Pro',
      'DaVinci Resolve',
      'After Effects',
      'Color Correction',
      'Audio Editing',
      'Motion Graphics',
      'Storytelling',
      'Cinematography Basics',
      'File Management',
    ],
  },
  {
    job: 'Motion Graphics Designer',
    requiredSkills: [
      'After Effects',
      'Cinema 4D',
      'Adobe Creative Suite',
      'Animation Principles',
      'Typography in Motion',
      'Visual Effects',
      'Compositing',
      'Storyboarding',
      'Brand Animation',
      'Creativity',
    ],
  },
  {
    job: 'Art Director',
    requiredSkills: [
      'Creativity',
      'Brand Strategy',
      'Communication',
      'Adobe Creative Suite',
      'Typography',
      'Layout Design',
      'Team Management',
      'Client Relations',
      'Campaign Development',
      'Trend Analysis',
    ],
  },
  {
    job: 'Illustrator',
    requiredSkills: [
      'Drawing Fundamentals',
      'Adobe Illustrator',
      'Digital Illustration',
      'Traditional Media',
      'Concept Development',
      'Character Design',
      'Editorial Illustration',
      'Book Illustration',
      'Storytelling',
      'Portfolio Development',
    ],
  },
  {
    job: 'Photographer',
    requiredSkills: [
      'Camera Operation',
      'Lighting Techniques',
      'Composition',
      'Photo Editing (Lightroom/Photoshop)',
      'Color Theory',
      'Portrait Photography',
      'Landscape Photography',
      'Commercial Photography',
      'Client Relations',
      'Business Skills',
    ],
  },
  {
    job: 'Fashion Designer',
    requiredSkills: [
      'Fashion Sketching',
      'Pattern Making',
      'Sewing',
      'Textile Knowledge',
      'Color Theory',
      'Trend Forecasting',
      'Fashion History',
      'Adobe Illustrator',
      'Draping',
      'Garment Construction',
      'Brand Development',
    ],
  },
  {
    job: 'Interior Designer',
    requiredSkills: [
      'Space Planning',
      'AutoCAD',
      'SketchUp',
      '3D Rendering',
      'Color Theory',
      'Material Selection',
      'Building Codes',
      'Client Relations',
      'Project Management',
      'Furniture Design',
      'Lighting Design',
    ],
  },
  {
    job: 'Industrial Designer',
    requiredSkills: [
      'Product Design',
      '3D Modeling (SolidWorks/Rhino)',
      'Sketching',
      'Prototyping',
      'Materials Knowledge',
      'Manufacturing Processes',
      'User-Centered Design',
      'CAD Software',
      'Design Research',
    ],
  },
  {
    job: 'Game Artist',
    requiredSkills: [
      'Concept Art',
      '3D Modeling',
      'Texturing',
      'Game Engines (Unity/Unreal)',
      'Digital Sculpting',
      'Character Design',
      'Environment Art',
      'Animation Basics',
      'Level Design',
      'Portfolio Development',
    ],
  },
  {
    job: 'Museum Curator',
    requiredSkills: [
      'Art History',
      'Research Skills',
      'Exhibition Planning',
      'Collection Management',
      'Grant Writing',
      'Public Speaking',
      'Academic Writing',
      'Museum Studies',
      'Cultural Preservation',
      'Project Management',
    ],
  },
  {
    job: 'Art Teacher/Professor',
    requiredSkills: [
      'Teaching Skills',
      'Curriculum Development',
      'Art History',
      'Studio Practice',
      'Classroom Management',
      'Assessment Methods',
      'Educational Technology',
      'Student Mentorship',
      'Professional Development',
    ],
  },
  {
    job: 'Creative Writer',
    requiredSkills: [
      'Writing Skills',
      'Storytelling',
      'Grammar',
      'Research',
      'Genre Knowledge',
      'Editing',
      'Publishing Industry Knowledge',
      'Digital Marketing',
      'Social Media',
      'Manuscript Formatting',
      'Creativity',
    ],
  },
  {
    job: 'Copywriter',
    requiredSkills: [
      'Persuasive Writing',
      'Brand Voice',
      'Marketing Strategy',
      'SEO Writing',
      'Social Media Content',
      'Campaign Development',
      'Research Skills',
      'Client Communication',
      'A/B Testing',
      'Digital Marketing',
    ],
  },
  {
    job: 'Content Creator',
    requiredSkills: [
      'Social Media Platforms',
      'Video Production',
      'Photography',
      'Content Strategy',
      'Analytics',
      'Brand Development',
      'Audience Engagement',
      'SEO',
      'Graphic Design Basics',
      'Storytelling',
    ],
  },
  {
    job: 'Art Therapist',
    requiredSkills: [
      'Psychology',
      'Art Therapy Techniques',
      'Human Development',
      'Group Facilitation',
      'Assessment Skills',
      'Ethical Practice',
      'Cultural Competency',
      'Documentation',
      'Crisis Intervention',
      'Continuing Education',
    ],
  },
  {
    job: 'Arts Administrator',
    requiredSkills: [
      'Arts Management',
      'Budget Management',
      'Grant Writing',
      'Marketing',
      'Event Planning',
      'Fundraising',
      'Volunteer Coordination',
      'Strategic Planning',
      'Community Outreach',
      'Database Management',
    ],
  },
  {
    job: 'Sound Designer',
    requiredSkills: [
      'Audio Software (Pro Tools/Logic/Ableton)',
      'Sound Editing',
      'Music Theory',
      'Recording Techniques',
      'Foley Art',
      'Audio Post-Production',
      'Sound Effects Creation',
      'Mixing',
      'Mastering',
    ],
  },
  {
    job: 'Music Producer',
    requiredSkills: [
      'Music Software (DAW)',
      'Mixing',
      'Mastering',
      'Music Theory',
      'Arrangement',
      'Recording Techniques',
      'Audio Engineering',
      'Artist Development',
      'Music Business',
      'Creativity',
    ],
  },
  {
    job: 'Architect',
    requiredSkills: [
      'AutoCAD',
      'Revit',
      'SketchUp',
      'Building Codes',
      'Structural Knowledge',
      'Project Management',
      'Space Planning',
      'Sustainable Design',
      'Client Relations',
      'Construction Documentation',
      '3D Visualization',
    ],
  },
  {
    job: 'Landscape Architect',
    requiredSkills: [
      'Site Planning',
      'AutoCAD',
      'SketchUp',
      'Plant Knowledge',
      'Environmental Design',
      'Sustainability',
      'GIS Software',
      'Project Management',
      'Construction Documentation',
      'Irrigation Systems',
    ],
  },
  {
    job: 'Film Director',
    requiredSkills: [
      'Storytelling',
      'Cinematography',
      'Script Analysis',
      'Leadership',
      'Creativity',
      'Budgeting',
      'Scheduling',
      'Casting',
      'Post-Production Knowledge',
      'Collaboration',
      'Communication',
    ],
  },
  {
    job: 'Cinematographer',
    requiredSkills: [
      'Camera Operation',
      'Lighting Design',
      'Visual Storytelling',
      'Color Theory',
      'Lens Selection',
      'Camera Movement',
      'Collaboration with Directors',
      'Technical Problem Solving',
      'Equipment Knowledge',
    ],
  },
  {
    job: 'Screenwriter',
    requiredSkills: [
      'Script Writing',
      'Story Structure',
      'Character Development',
      'Dialogue Writing',
      'Genre Knowledge',
      'Industry Standards',
      'Pitching Skills',
      'Collaboration',
      'Revision Skills',
      'Market Awareness',
    ],
  },
  {
    job: 'Film Editor',
    requiredSkills: [
      'Editing Software (Avid/Premiere/Final Cut)',
      'Storytelling',
      'Pacing',
      'Color Correction',
      'Sound Design',
      'Collaboration',
      'Problem Solving',
      'Technical Skills',
      'Attention to Detail',
    ],
  },
  {
    job: 'Production Designer',
    requiredSkills: [
      'Set Design',
      'Art Direction',
      'Visual Storytelling',
      'Sketching',
      '3D Visualization',
      'Budget Management',
      'Collaboration',
      'Research Skills',
      'Historical Knowledge',
      'Material Selection',
    ],
  },
  {
    job: 'Costume Designer',
    requiredSkills: [
      'Fashion Design',
      'Historical Research',
      'Fabric Knowledge',
      'Sewing Skills',
      'Character Analysis',
      'Collaboration',
      'Sketching',
      'Budget Management',
      'Wardrobe Supervision',
      'Color Theory',
    ],
  },
  {
    job: 'Makeup Artist',
    requiredSkills: [
      'Makeup Techniques',
      'Color Theory',
      'Anatomy Knowledge',
      'Special Effects Makeup',
      'Product Knowledge',
      'Hygiene Practices',
      'Client Relations',
      'Time Management',
      'Photography Makeup',
    ],
  },
  {
    job: 'Hair Stylist',
    requiredSkills: [
      'Hair Cutting',
      'Coloring',
      'Styling',
      'Product Knowledge',
      'Trends',
      'Client Consultation',
      'Sanitation',
      'Business Skills',
      'Continuing Education',
      'Creativity',
    ],
  },
  {
    job: 'Tattoo Artist',
    requiredSkills: [
      'Drawing Skills',
      'Tattoo Techniques',
      'Hygiene Protocols',
      'Customer Service',
      'Business Management',
      'Portfolio Development',
      'Equipment Maintenance',
      'Safety Procedures',
      'Artistic Style',
    ],
  },
  {
    job: 'Jewelry Designer',
    requiredSkills: [
      'Metalworking',
      'Gem Setting',
      'CAD Design',
      'Hand Sketching',
      'Materials Knowledge',
      'Business Skills',
      'Portfolio Development',
      'Custom Design',
      'Repair Skills',
      'Market Trends',
    ],
  },
  {
    job: 'Ceramic Artist',
    requiredSkills: [
      'Clay Working',
      'Glazing Techniques',
      'Kiln Operation',
      'Sculpture Skills',
      'Pottery Wheel',
      'Surface Decoration',
      'Business Skills',
      'Exhibition Preparation',
      'Material Knowledge',
    ],
  },
  {
    job: 'Textile Designer',
    requiredSkills: [
      'Pattern Design',
      'Color Theory',
      'Fabric Knowledge',
      'Print Design',
      'Computer-Aided Design',
      'Trend Forecasting',
      'Technical Drawing',
      'Material Testing',
      'Production Knowledge',
    ],
  },
  {
    job: 'Calligrapher',
    requiredSkills: [
      'Hand Lettering',
      'Typography',
      'Brushwork',
      'Ink Knowledge',
      'Design Layout',
      'Historical Scripts',
      'Custom Design',
      'Business Skills',
      'Digital Tools',
      'Paper Selection',
    ],
  },
  {
    job: 'Stained Glass Artist',
    requiredSkills: [
      'Glass Cutting',
      'Soldering',
      'Lead Work',
      'Design Skills',
      'Color Theory',
      'Historical Techniques',
      'Restoration Skills',
      'Safety Procedures',
      'Client Relations',
      'Installation',
    ],
  },
  {
    job: 'Woodworker/Furniture Maker',
    requiredSkills: [
      'Wood Selection',
      'Hand Tools',
      'Power Tools',
      'Joinery Techniques',
      'Finishing',
      'Design Skills',
      'Math Skills',
      'Safety Procedures',
      'Business Management',
      'Custom Work',
    ],
  },
  {
    job: 'Sculptor',
    requiredSkills: [
      '3D Design',
      'Material Knowledge',
      'Tool Proficiency',
      'Anatomy',
      'Proportion',
      'Space Relationships',
      'Installation Skills',
      'Portfolio Development',
      'Grant Writing',
      'Exhibition Planning',
    ],
  },
  {
    job: 'Mural Artist',
    requiredSkills: [
      'Large-Scale Painting',
      'Surface Preparation',
      'Weather-Resistant Materials',
      'Composition',
      'Public Art Regulations',
      'Community Engagement',
      'Project Management',
      'Safety Equipment',
    ],
  },
  {
    job: 'Street Artist',
    requiredSkills: [
      'Urban Art Techniques',
      'Legal Knowledge',
      'Community Engagement',
      'Social Commentary',
      'Material Innovation',
      'Documentation',
      'Gallery Transition',
      'Brand Development',
    ],
  },
  {
    job: 'Book Designer',
    requiredSkills: [
      'Typography',
      'Layout Design',
      'Adobe InDesign',
      'Print Production',
      'Publishing Process',
      'Genre Conventions',
      'Collaboration with Authors/Editors',
      'Marketing Materials',
    ],
  },
  {
    job: 'Magazine Designer',
    requiredSkills: [
      'Editorial Design',
      'Typography',
      'Layout',
      'Adobe Creative Suite',
      'Deadline Management',
      'Brand Consistency',
      'Photo Direction',
      'Digital Publishing',
      'Print Production',
    ],
  },
  {
    job: 'Brand Designer',
    requiredSkills: [
      'Brand Strategy',
      'Logo Design',
      'Visual Identity Systems',
      'Typography',
      'Color Systems',
      'Brand Guidelines',
      'Market Research',
      'Client Presentation',
      'Implementation',
    ],
  },
  {
    job: 'Exhibition Designer',
    requiredSkills: [
      'Spatial Design',
      'Lighting Design',
      'Visitor Flow',
      'Accessibility',
      'Interactive Design',
      'Fabrication Knowledge',
      'Project Management',
      'Collaboration',
      'Safety Regulations',
    ],
  },
  {
    job: 'Set Decorator',
    requiredSkills: [
      'Interior Design',
      'Prop Selection',
      'Historical Research',
      'Budget Management',
      'Collaboration',
      'Problem Solving',
      'Attention to Detail',
      'Shopping Skills',
      'Inventory Management',
    ],
  },
  {
    job: 'Prop Master',
    requiredSkills: [
      'Crafting Skills',
      'Problem Solving',
      'Research',
      'Budget Management',
      'Organization',
      'Collaboration',
      'Safety Knowledge',
      'Tool Proficiency',
      'Creativity',
      'Time Management',
    ],
  },
  {
    job: 'Lighting Designer',
    requiredSkills: [
      'Lighting Technology',
      'Color Theory',
      'Electrical Knowledge',
      'Design Software',
      'Collaboration',
      'Problem Solving',
      'Safety Procedures',
      'Equipment Knowledge',
      'Creativity',
    ],
  },
  {
    job: 'Stage Manager',
    requiredSkills: [
      'Organization Skills',
      'Communication',
      'Problem Solving',
      'Technical Knowledge',
      'Leadership',
      'Scheduling',
      'Safety Procedures',
      'Collaboration',
      'Attention to Detail',
      'Multitasking',
    ],
  },
  {
    job: 'Theater Director',
    requiredSkills: [
      'Leadership',
      'Script Analysis',
      'Casting',
      'Collaboration',
      'Creativity',
      'Communication',
      'Problem Solving',
      'Budget Awareness',
      'Scheduling',
      'Artistic Interpretation',
    ],
  },
  {
    job: 'Choreographer',
    requiredSkills: [
      'Dance Techniques',
      'Movement Analysis',
      'Music Knowledge',
      'Creativity',
      'Teaching Skills',
      'Collaboration',
      'Choreographic Notation',
      'Performance Experience',
      'Cultural Awareness',
    ],
  },
  {
    job: 'Dance Teacher',
    requiredSkills: [
      'Dance Techniques',
      'Teaching Methods',
      'Anatomy',
      'Injury Prevention',
      'Music Knowledge',
      'Choreography',
      'Student Assessment',
      'Class Management',
      'Continuing Education',
    ],
  },
  {
    job: 'Voice Coach',
    requiredSkills: [
      'Vocal Techniques',
      'Anatomy',
      'Music Theory',
      'Performance Skills',
      'Teaching Methods',
      'Ear Training',
      'Breath Control',
      'Repertoire Knowledge',
      'Student Assessment',
    ],
  },
  {
    job: 'Drama Therapist',
    requiredSkills: [
      'Theater Techniques',
      'Psychology',
      'Group Facilitation',
      'Assessment Skills',
      'Therapeutic Methods',
      'Ethical Practice',
      'Documentation',
      'Crisis Intervention',
      'Cultural Competency',
    ],
  },
  {
    job: 'Music Therapist',
    requiredSkills: [
      'Music Skills',
      'Psychology',
      'Assessment',
      'Therapeutic Techniques',
      'Instrument Proficiency',
      'Documentation',
      'Ethical Practice',
      'Cultural Competency',
      'Continuing Education',
    ],
  },
  {
    job: 'Radio Host/DJ',
    requiredSkills: [
      'Broadcasting Skills',
      'Music Knowledge',
      'Audio Equipment',
      'Interviewing',
      'Improvisation',
      'Voice Training',
      'Social Media',
      'Audience Engagement',
      'Technical Operations',
    ],
  },
  {
    job: 'Podcast Producer',
    requiredSkills: [
      'Audio Production',
      'Storytelling',
      'Interviewing',
      'Marketing',
      'Social Media',
      'Analytics',
      'Budget Management',
      'Scheduling',
      'Research Skills',
      'Technical Problem Solving',
    ],
  },
  {
    job: 'Creative Director',
    requiredSkills: [
      'Creativity',
      'Leadership',
      'Brand Strategy',
      'Campaign Development',
      'Team Management',
      'Client Relations',
      'Trend Analysis',
      'Budget Management',
      'Presentation Skills',
      'Project Management',
    ],
  },
  {
    job: 'Art Gallery Owner',
    requiredSkills: [
      'Business Management',
      'Art Market Knowledge',
      'Networking',
      'Curation',
      'Marketing',
      'Financial Management',
      'Artist Relations',
      'Event Planning',
      'Sales Skills',
      'Trend Analysis',
    ],
  },
  {
    job: 'Art Dealer',
    requiredSkills: [
      'Market Knowledge',
      'Networking',
      'Sales Skills',
      'Authentication',
      'Valuation',
      'Client Relations',
      'Art History',
      'Negotiation',
      'Documentation',
      'Trend Analysis',
    ],
  },
  {
    job: 'Art Conservator',
    requiredSkills: [
      'Chemistry Knowledge',
      'Art History',
      'Technical Skills',
      'Documentation',
      'Problem Solving',
      'Attention to Detail',
      'Research Skills',
      'Ethical Practice',
      'Continuing Education',
    ],
  },
  {
    job: 'Arts Journalist',
    requiredSkills: [
      'Writing Skills',
      'Art Knowledge',
      'Research',
      'Interviewing',
      'Deadline Management',
      'Digital Media',
      'Photography',
      'Networking',
      'Critical Analysis',
      'Cultural Awareness',
    ],
  },
  {
    job: 'Documentary Filmmaker',
    requiredSkills: [
      'Research Skills',
      'Interviewing',
      'Storytelling',
      'Camera Operation',
      'Editing',
      'Fundraising',
      'Project Management',
      'Ethical Considerations',
      'Distribution Knowledge',
    ],
  },
  {
    job: 'Event Planner',
    requiredSkills: [
      'Organization',
      'Budget Management',
      'Vendor Relations',
      'Timeline Management',
      'Problem Solving',
      'Communication',
      'Creativity',
      'Negotiation',
      'Marketing',
      'Customer Service',
    ],
  },
  {
    job: 'Wedding Planner',
    requiredSkills: [
      'Event Planning',
      'Design Skills',
      'Vendor Management',
      'Budget Control',
      'Timeline Coordination',
      'Problem Solving',
      'Customer Service',
      'Stress Management',
      'Attention to Detail',
    ],
  },
  {
    job: 'Floral Designer',
    requiredSkills: [
      'Floral Arrangement',
      'Color Theory',
      'Plant Knowledge',
      'Design Principles',
      'Customer Service',
      'Business Skills',
      'Seasonal Awareness',
      'Tools Proficiency',
      'Creativity',
    ],
  },
  {
    job: 'Window Display Designer',
    requiredSkills: [
      'Visual Merchandising',
      'Retail Knowledge',
      'Lighting Design',
      'Color Theory',
      'Trend Awareness',
      'Space Planning',
      'Customer Psychology',
      'Seasonal Design',
      'Installation Skills',
    ],
  },
  {
    job: 'Visual Merchandiser',
    requiredSkills: [
      'Retail Design',
      'Consumer Psychology',
      'Trend Analysis',
      'Display Techniques',
      'Space Planning',
      'Brand Understanding',
      'Sales Knowledge',
      'Inventory Management',
      'Team Collaboration',
    ],
  },
  {
    job: 'Retail Store Designer',
    requiredSkills: [
      'Retail Psychology',
      'Space Planning',
      'Customer Flow',
      'Brand Translation',
      'Budget Management',
      'Construction Knowledge',
      'Lighting Design',
      'Materials Selection',
      'Project Management',
    ],
  },
  {
    job: 'Experience Designer',
    requiredSkills: [
      'User Experience',
      'Psychology',
      'Creativity',
      'Prototyping',
      'Research Methods',
      'Storytelling',
      'Technology Integration',
      'Project Management',
      'Collaboration',
    ],
  },
  {
    job: 'Service Designer',
    requiredSkills: [
      'Design Thinking',
      'User Research',
      'Journey Mapping',
      'Prototyping',
      'Systems Thinking',
      'Stakeholder Management',
      'Workshop Facilitation',
      'Business Strategy',
      'Process Improvement',
    ],
  },
  {
    job: 'Creative Technologist',
    requiredSkills: [
      'Programming Skills',
      'Creativity',
      'Emerging Technologies',
      'Problem Solving',
      'Art Direction',
      'Technical Innovation',
      'Collaboration',
      'Rapid Prototyping',
      'Trend Awareness',
    ],
  },
  {
    job: 'Digital Media Artist',
    requiredSkills: [
      'Digital Art Software',
      'Interactive Media',
      'Programming Basics',
      'New Media Technologies',
      'Conceptual Thinking',
      'Technical Problem Solving',
      'Installation Skills',
      'Portfolio Development',
    ],
  },
  {
    job: 'Virtual Reality Artist',
    requiredSkills: [
      '3D Modeling',
      'VR Software (Unity/Unreal)',
      'Programming',
      'User Experience',
      'Spatial Design',
      'Interactive Storytelling',
      'Technical Problem Solving',
      'Emerging Technologies',
    ],
  },
  {
    job: 'Augmented Reality Designer',
    requiredSkills: [
      'AR Development',
      '3D Design',
      'Programming',
      'User Experience',
      'Mobile Design',
      'Spatial Computing',
      'Technical Innovation',
      'User Testing',
      'Emerging Technologies',
    ],
  },
  {
    job: 'Social Media Manager',
    requiredSkills: [
      'Content Creation',
      'Community Management',
      'Social Media Strategy',
      'Analytics Tools (Sprout Social',
      'Hootsuite)',
      'SEO Basics',
      'Paid Advertising',
      'Engagement Analysis',
      'Communication',
      'Creativity',
      'Branding',
      'Platform Knowledge',
      'Visual Design',
      'Campaign Planning',
      'Trend Awareness',
      'Customer Service'
    ],
  },
  {
    job: 'Influencer/Content Creator',
    requiredSkills: [
      'Personal Branding',
      'Content Strategy',
      'Video Production',
      'Photography',
      'Social Media',
      'Audience Engagement',
      'Partnership Management',
      'Analytics',
      'Trend Awareness',
    ],
  },
  {
    job: 'YouTuber/Video Creator',
    requiredSkills: [
      'Video Production',
      'Editing',
      'Thumbnails Design',
      'SEO',
      'Analytics',
      'Audience Development',
      'Monetization Strategies',
      'Consistency',
      'Creative Content Development',
    ],
  },
  {
    job: 'Twitch Streamer',
    requiredSkills: [
      'Live Streaming',
      'Community Building',
      'Gaming Skills',
      'Entertainment Skills',
      'Technical Setup',
      'Brand Development',
      'Audience Engagement',
      'Consistency',
      'Marketing',
    ],
  },
  {
    job: 'TikTok Creator',
    requiredSkills: [
      'Short-form Video',
      'Trend Awareness',
      'Editing Skills',
      'Music Selection',
      'Audience Engagement',
      'Hashtag Strategy',
      'Analytics',
      'Creativity',
      'Consistency',
    ],
  },
  {
    job: 'Instagram Content Creator',
    requiredSkills: [
      'Photography',
      'Visual Storytelling',
      'Hashtag Strategy',
      'Stories Creation',
      'Reels Production',
      'Audience Engagement',
      'Brand Partnerships',
      'Analytics',
      'Consistency',
    ],
  },
  {
    job: 'Freelance Artist',
    requiredSkills: [
      'Self-Management',
      'Business Skills',
      'Client Relations',
      'Portfolio Development',
      'Marketing',
      'Pricing Strategy',
      'Contract Knowledge',
      'Time Management',
      'Financial Management',
    ],
  },
  {
    job: 'Commission Artist',
    requiredSkills: [
      'Custom Art Creation',
      'Client Consultation',
      'Project Management',
      'Portfolio Presentation',
      'Pricing',
      'Communication',
      'Revision Management',
      'Business Administration',
    ],
  },
  {
    job: 'NFT Artist',
    requiredSkills: [
      'Digital Art',
      'Blockchain Knowledge',
      'Cryptocurrency',
      'Online Marketing',
      'Community Building',
      'Platform Knowledge',
      'Technical Skills',
      'Market Understanding',
      'Brand Development',
    ],
  },
  {
    job: 'Concept Artist',
    requiredSkills: [
      'Digital Painting',
      '3D Understanding',
      'Visual Development',
      'Collaboration',
      'Research Skills',
      'Style Adaptation',
      'Speed Sketching',
      'Industry Knowledge',
      'Portfolio Development',
    ],
  },
  {
    job: 'Character Designer',
    requiredSkills: [
      'Drawing Skills',
      'Anatomy',
      'Character Development',
      'Storytelling',
      'Style Consistency',
      'Research',
      'Collaboration',
      'Revision Skills',
      'Industry Knowledge',
      'Portfolio Curation',
    ],
  },
  {
    job: 'Environment Artist',
    requiredSkills: [
      'Landscape Design',
      'Architectural Understanding',
      'Lighting Knowledge',
      'Mood Creation',
      'Research Skills',
      'Technical Proficiency',
      'Collaboration',
      'World Building',
      'Portfolio Development',
    ],
  },
  {
    job: 'Storyboard Artist',
    requiredSkills: [
      'Sequential Art',
      'Cinematography Understanding',
      'Drawing Speed',
      'Visual Storytelling',
      'Collaboration',
      'Industry Software',
      'Revision Skills',
      'Time Management',
      'Communication',
    ],
  },
  {
    job: 'Comic Book Artist',
    requiredSkills: [
      'Sequential Art',
      'Character Consistency',
      'Storytelling',
      'Inking',
      'Coloring',
      'Panel Layout',
      'Collaboration',
      'Deadline Management',
      'Industry Knowledge',
      'Portfolio Development',
    ],
  },
  {
    job: "Children's Book Illustrator",
    requiredSkills: [
      'Child Psychology Understanding',
      'Storytelling',
      'Character Design',
      'Collaboration with Authors',
      'Publishing Knowledge',
      'Age-Appropriate Content',
      'Portfolio Development',
    ],
  },
  {
    job: 'Editorial Illustrator',
    requiredSkills: [
      'Concept Visualization',
      'Quick Turnaround',
      'Style Versatility',
      'Current Events Awareness',
      'Collaboration with Editors',
      'Portfolio Maintenance',
      'Business Skills',
    ],
  },
  {
    job: 'Medical Illustrator',
    requiredSkills: [
      'Anatomy Knowledge',
      'Scientific Accuracy',
      'Technical Drawing',
      'Collaboration with Medical Professionals',
      'Software Proficiency',
      'Attention to Detail',
      'Continuing Education',
    ],
  },
  {
    job: 'Scientific Illustrator',
    requiredSkills: [
      'Scientific Knowledge',
      'Technical Accuracy',
      'Research Skills',
      'Collaboration with Scientists',
      'Specialized Software',
      'Portfolio Development',
      'Continuing Education',
    ],
  },
  {
    job: 'Technical Illustrator',
    requiredSkills: [
      'Technical Understanding',
      'Precision Drawing',
      'CAD Knowledge',
      'Instruction Creation',
      'Collaboration with Engineers',
      'Software Proficiency',
      'Attention to Detail',
    ],
  },
  {
    job: 'Archaeological Illustrator',
    requiredSkills: [
      'Archaeological Knowledge',
      'Scientific Drawing',
      'Field Work Skills',
      'Documentation',
      'Collaboration with Archaeologists',
      'Historical Research',
      'Technical Accuracy',
    ],
  },
  {
    job: 'Courtroom Artist',
    requiredSkills: [
      'Quick Sketching',
      'Observation Skills',
      'Legal Knowledge',
      'Deadline Pressure',
      'Media Relations',
      'Discretion',
      'Accuracy',
      'Portfolio Maintenance',
      'Professional Conduct',
    ],
  },
  {
    "job": "Accountant",
    "requiredSkills": [
      "Financial Accounting",
      "Bookkeeping",
      "Accounts Payable",
      "Accounts Receivable",
      "General Ledger",
      "Bank Reconciliation",
      "Payroll",
      "MS Excel",
      "Tally ERP",
      "QuickBooks",
      "Financial Reporting",
      "Compliance",
      "Communication"
    ]
  },
  {
    "job": "Financial Analyst",
    "requiredSkills": [
      "Financial Modeling",
      "Data Analysis",
      "MS Excel (Advanced)",
      "Budgeting",
      "Forecasting",
      "Valuation",
      "Investment Analysis",
      "Financial Reporting",
      "Power BI/Tableau",
      "SQL",
      "Communication",
      "Problem Solving",
      "Presentation Skills"
    ]
  },
  {
    "job": "Auditor",
    "requiredSkills": [
      "Internal Audit",
      "External Audit",
      "Risk Assessment",
      "Compliance",
      "GAAP",
      "IFRS",
      "Taxation Basics",
      "SAP",
      "Documentation",
      "Attention to Detail",
      "Communication",
      "Analytical Skills"
    ]
  },
  {
    "job": "Tax Consultant",
    "requiredSkills": [
      "Direct Tax",
      "Indirect Tax (GST",
      "VAT)",
      "Income Tax Filing",
      "Tax Planning",
      "Transfer Pricing",
      "Tally",
      "MS Excel",
      "Regulatory Compliance",
      "Analytical Thinking",
      "Problem Solving",
      "Client Communication"
    ]
  },
  {
    "job": "Investment Banker",
    "requiredSkills": [
      "Financial Modeling",
      "Valuation (DCF",
      "LBO",
      "Comparable Analysis)",
      "M&A",
      "Capital Markets",
      "Deal Structuring",
      "Presentation Skills",
      "MS Excel",
      "PowerPoint",
      "Bloomberg Terminal",
      "Negotiation",
      "Communication",
      "Analytical Skills"
    ]
  },
  {
    "job": "Risk Manager",
    "requiredSkills": [
      "Risk Assessment",
      "Credit Risk",
      "Market Risk",
      "Operational Risk",
      "Basel Norms",
      "Compliance",
      "Data Analysis",
      "Statistical Tools",
      "Financial Reporting",
      "Problem Solving",
      "Communication"
    ]
  },
  {
    "job": "Corporate Finance Manager",
    "requiredSkills": [
      "Financial Planning",
      "Treasury Management",
      "Working Capital",
      "Debt/Equity Financing",
      "Mergers & Acquisitions",
      "Valuation",
      "Budgeting",
      "Financial Modeling",
      "Compliance",
      "Leadership",
      "Communication"
    ]
  },
  {
    "job": "Cost Accountant",
    "requiredSkills": [
      "Cost Accounting",
      "Budgeting",
      "Variance Analysis",
      "Standard Costing",
      "Cost Control",
      "Tally ERP",
      "MS Excel",
      "Reporting",
      "Problem Solving",
      "Documentation"
    ]
  },
  {
    "job": "Chartered Accountant (CA)",
    "requiredSkills": [
      "Accounting Standards",
      "Auditing",
      "Taxation",
      "Corporate Laws",
      "Compliance",
      "Financial Reporting",
      "Risk Management",
      "SAP",
      "Tally",
      "Communication",
      "Problem Solving",
      "Analytical Skills"
    ]
  },
  {
    "job": "Financial Planner",
    "requiredSkills": [
      "Wealth Management",
      "Investment Advisory",
      "Retirement Planning",
      "Insurance Planning",
      "Estate Planning",
      "Financial Modeling",
      "Client Communication",
      "Negotiation",
      "Analytical Skills"
    ]
  },
  {
    "job": "Banking Officer",
    "requiredSkills": [
      "Retail Banking",
      "Corporate Banking",
      "Loan Processing",
      "Risk Management",
      "Customer Relationship",
      "Compliance",
      "Core Banking Systems",
      "MS Excel",
      "Communication",
      "Problem Solving"
    ]
  },
  {
    "job": "Credit Analyst",
    "requiredSkills": [
      "Credit Risk Analysis",
      "Financial Statement Analysis",
      "Ratio Analysis",
      "Cash Flow Analysis",
      "Loan Underwriting",
      "Risk Assessment",
      "Compliance",
      "MS Excel",
      "Analytical Skills",
      "Communication"
    ]
  },
  {
    "job": "Equity Research Analyst",
    "requiredSkills": [
      "Equity Valuation",
      "Financial Modeling",
      "Fundamental Analysis",
      "Technical Analysis",
      "Bloomberg Terminal",
      "Data Analysis",
      "MS Excel",
      "PowerPoint",
      "Report Writing",
      "Communication",
      "Presentation"
    ]
  },
  {
    "job": "Treasury Analyst",
    "requiredSkills": [
      "Cash Management",
      "Liquidity Management",
      "Hedging",
      "Forex",
      "Risk Management",
      "Banking Operations",
      "Financial Reporting",
      "MS Excel",
      "SAP",
      "Analytical Skills",
      "Communication"
    ]
  },
  {
    "job": "Economist",
    "requiredSkills": [
      "Economic Theory",
      "Microeconomics",
      "Macroeconomics",
      "Econometrics",
      "Statistical Analysis",
      "Data Analysis (R",
      "Python",
      "Stata",
      "SPSS)",
      "Forecasting",
      "Research Methodology",
      "Policy Analysis",
      "Report Writing",
      "Critical Thinking",
      "Communication"
    ]
  },
  {
    "job": "Economic Analyst",
    "requiredSkills": [
      "Data Analysis",
      "Econometrics",
      "Regression Modeling",
      "Forecasting",
      "Policy Evaluation",
      "Financial Economics",
      "R/Python/Excel",
      "Visualization (Tableau",
      "Power BI)",
      "Problem Solving",
      "Report Writing",
      "Presentation Skills"
    ]
  },
  {
    "job": "Business Analyst",
    "requiredSkills": [
      "Requirements Gathering",
      "Business Process Analysis",
      "Data Analysis (Excel",
      "SQL",
      "Python)",
      "Financial Analysis",
      "Reporting",
      "Stakeholder Management",
      "Problem Solving",
      "Communication",
      "Agile/Scrum",
      "Critical Thinking"
    ]
  },
  {
    "job": "Management Consultant",
    "requiredSkills": [
      "Strategy Development",
      "Business Analysis",
      "Market Research",
      "Financial Analysis",
      "Project Management",
      "Excel",
      "PowerPoint",
      "Problem Solving",
      "Critical Thinking",
      "Communication",
      "Client Interaction",
      "Presentation Skills"
    ]
  },
  {
    "job": "Operations Manager",
    "requiredSkills": [
      "Process Optimization",
      "Supply Chain Management",
      "Lean Management",
      "Six Sigma",
      "Project Management",
      "ERP Tools (SAP",
      "Oracle)",
      "Leadership",
      "Team Management",
      "Analytical Thinking",
      "Communication",
      "Decision Making"
    ]
  },
  {
    "job": "Project Manager",
    "requiredSkills": [
      "Project Planning",
      "Scheduling",
      "Risk Management",
      "Resource Allocation",
      "Budgeting",
      "MS Project",
      "Primavera",
      "Agile/Scrum",
      "Team Leadership",
      "Communication",
      "Reporting",
      "Stakeholder Management"
    ]
  },
  {
    "job": "Marketing Manager",
    "requiredSkills": [
      "Market Research",
      "Digital Marketing",
      "SEO/SEM",
      "Social Media Strategy",
      "Brand Management",
      "Analytics Tools (Google Analytics",
      "Tableau)",
      "Communication",
      "Creativity",
      "Campaign Management",
      "Strategic Thinking"
    ]
  },
  {
    "job": "Human Resource Manager",
    "requiredSkills": [
      "Talent Acquisition",
      "Employee Relations",
      "HR Policies",
      "Payroll Management",
      "Performance Management",
      "HR Software (SAP HR",
      "Workday)",
      "Communication",
      "Leadership",
      "Conflict Resolution",
      "Training & Development"
    ]
  },
  {
    "job": "Financial Manager",
    "requiredSkills": [
      "Financial Analysis",
      "Budgeting",
      "Forecasting",
      "Risk Management",
      "Accounting",
      "Excel",
      "ERP Tools",
      "Strategic Planning",
      "Investment Analysis",
      "Communication",
      "Decision Making"
    ]
  },
  {
    "job": "Operations Analyst",
    "requiredSkills": [
      "Process Mapping",
      "Data Analysis",
      "Excel",
      "SQL",
      "Lean/Six Sigma",
      "Reporting",
      "KPI Tracking",
      "Problem Solving",
      "Process Improvement",
      "Communication"
    ]
  },
  {
    "job": "Strategic Planner",
    "requiredSkills": [
      "Market Analysis",
      "Business Strategy",
      "Forecasting",
      "Financial Modelling",
      "Competitive Analysis",
      "Excel",
      "PowerPoint",
      "Critical Thinking",
      "Communication",
      "Decision Making"
    ]
  },
  {
    "job": "Policy Analyst",
    "requiredSkills": [
      "Policy Research",
      "Statistical Analysis",
      "Econometrics",
      "Cost-Benefit Analysis",
      "Report Writing",
      "R/Python/Stata",
      "Communication",
      "Critical Thinking",
      "Presentation Skills",
      "Stakeholder Engagement"
    ]
  },
  {
    "job": "Supply Chain Manager",
    "requiredSkills": [
      "Logistics Management",
      "Inventory Control",
      "Demand Forecasting",
      "Procurement",
      "ERP Systems",
      "Lean/Six Sigma",
      "Negotiation",
      "Analytical Skills",
      "Team Management",
      "Communication"
    ]
  },
  {
    "job": "Operations Research Analyst",
    "requiredSkills": [
      "Optimization",
      "Linear Programming",
      "Simulation",
      "Statistics",
      "Data Analysis (R",
      "Python",
      "MATLAB)",
      "Problem Solving",
      "Reporting",
      "Communication",
      "Critical Thinking"
    ]
  },
  {
    "job": "Business Development Manager",
    "requiredSkills": [
      "Market Research",
      "Sales Strategy",
      "Client Acquisition",
      "Negotiation",
      "CRM Tools",
      "Communication",
      "Networking",
      "Strategic Planning",
      "Analytical Thinking"
    ]
  },
  {
    "job": "Entrepreneur / Startup Founder",
    "requiredSkills": [
      "Business Strategy",
      "Fundraising",
      "Marketing",
      "Operations",
      "Financial Planning",
      "Leadership",
      "Decision Making",
      "Networking",
      "Problem Solving",
      "Communication",
      "Innovation"
    ]
  },
  {
    "job": "Digital Marketing Manager",
    "requiredSkills": [
      "SEO",
      "SEM",
      "Social Media Marketing",
      "Content Marketing",
      "Google Analytics",
      "Facebook Ads",
      "Instagram Ads",
      "LinkedIn Marketing",
      "Email Marketing",
      "Marketing Automation Tools (HubSpot",
      "Mailchimp)",
      "Campaign Management",
      "Creativity",
      "Analytics",
      "Communication"
    ]
  },
  {
    "job": "Content Marketing Specialist",
    "requiredSkills": [
      "Copywriting",
      "Blogging",
      "SEO",
      "Content Strategy",
      "Content Management Systems (WordPress)",
      "Email Marketing",
      "Analytics (Google Analytics)",
      "Storytelling",
      "Creativity",
      "Social Media",
      "Communication"
    ]
  },
  {
    "job": "Brand Manager",
    "requiredSkills": [
      "Brand Strategy",
      "Market Research",
      "Consumer Behavior",
      "Product Positioning",
      "Marketing Campaigns",
      "Competitive Analysis",
      "Communication",
      "Leadership",
      "Creativity",
      "Project Management"
    ]
  },
  {
    "job": "Growth Hacker / Growth Marketing Specialist",
    "requiredSkills": [
      "Digital Marketing",
      "SEO",
      "SEM",
      "Social Media",
      "Email Marketing",
      "Conversion Rate Optimization",
      "A/B Testing",
      "Analytics (Google Analytics",
      "Mixpanel)",
      "Creativity",
      "Data-Driven Decision Making",
      "Experimentation"
    ]
  },
  {
    "job": "E-commerce Manager",
    "requiredSkills": [
      "Online Store Management",
      "Shopify/Magento/WooCommerce",
      "Digital Marketing",
      "Inventory Management",
      "SEO",
      "Analytics",
      "Customer Experience",
      "Campaign Management",
      "Communication",
      "Project Management"
    ]
  },
  {
    "job": "Startup Founder / Entrepreneur",
    "requiredSkills": [
      "Business Strategy",
      "Fundraising",
      "Marketing",
      "Operations",
      "Financial Planning",
      "Product Development",
      "Team Leadership",
      "Networking",
      "Innovation",
      "Risk Management",
      "Decision Making",
      "Communication"
    ]
  },
  {
    "job": "Business Development Executive",
    "requiredSkills": [
      "Lead Generation",
      "Sales Strategy",
      "Client Relationship Management",
      "Negotiation",
      "CRM Tools (Salesforce",
      "HubSpot)",
      "Market Research",
      "Communication",
      "Networking",
      "Problem Solving"
    ]
  },
  {
    "job": "Sales Manager",
    "requiredSkills": [
      "Sales Strategy",
      "Team Management",
      "Lead Generation",
      "CRM Tools",
      "Negotiation",
      "Forecasting",
      "Market Analysis",
      "Communication",
      "Presentation Skills",
      "Relationship Management"
    ]
  },
  {
    "job": "Marketing Analyst",
    "requiredSkills": [
      "Market Research",
      "Data Analysis",
      "Excel",
      "SQL",
      "Tableau/Power BI",
      "Consumer Insights",
      "Reporting",
      "SEO Basics",
      "Marketing Metrics",
      "Problem Solving",
      "Communication"
    ]
  },
  {
    "job": "Advertising Manager",
    "requiredSkills": [
      "Campaign Strategy",
      "Media Planning",
      "Digital Advertising",
      "Google Ads",
      "Social Media Ads",
      "Budget Management",
      "Creativity",
      "Communication",
      "Analytics",
      "Negotiation"
    ]
  },
  {
    "job": "Event Marketing Manager",
    "requiredSkills": [
      "Event Planning",
      "Marketing Strategy",
      "Budgeting",
      "Vendor Coordination",
      "Promotion",
      "Social Media Marketing",
      "Communication",
      "Project Management",
      "Creativity",
      "Negotiation"
    ]
  },
  {
    "job": "Procurement Manager",
    "requiredSkills": [
      "Vendor Selection",
      "Negotiation",
      "Contract Management",
      "Cost Analysis",
      "Procurement Processes",
      "ERP Tools",
      "Supplier Relationship Management",
      "Risk Assessment",
      "Compliance",
      "Communication"
    ]
  },
  {
    "job": "Logistics Manager",
    "requiredSkills": [
      "Transportation Management",
      "Warehousing",
      "Distribution Planning",
      "Inventory Control",
      "ERP Tools",
      "Route Optimization",
      "Supply Chain Analytics",
      "Communication",
      "Problem Solving"
    ]
  },
  {
    "job": "Insurance Analyst",
    "requiredSkills": [
      "Risk Assessment",
      "Policy Analysis",
      "Underwriting",
      "Claims Management",
      "Actuarial Analysis",
      "Financial Analysis",
      "Regulatory Compliance",
      "Excel",
      "Data Analysis",
      "Communication"
    ]
  },
  {
    "job": "Investment Advisor / Wealth Manager",
    "requiredSkills": [
      "Portfolio Management",
      "Financial Planning",
      "Investment Analysis",
      "Risk Assessment",
      "Mutual Funds",
      "Stocks & Bonds",
      "Retirement Planning",
      "Estate Planning",
      "Financial Modelling",
      "Client Communication",
      "Regulatory Compliance"
    ]
  },
  {
    "job": "Loan Officer / Banking Officer",
    "requiredSkills": [
      "Credit Assessment",
      "Loan Processing",
      "Customer Service",
      "Banking Operations",
      "Compliance",
      "Risk Assessment",
      "Financial Analysis",
      "Communication",
      "Negotiation"
    ]
  },
  {
    "job": "Compliance Officer",
    "requiredSkills": [
      "Regulatory Compliance",
      "Risk Management",
      "Internal Audits",
      "Policy Development",
      "Anti-Money Laundering (AML)",
      "Know Your Customer (KYC)",
      "Reporting",
      "Excel",
      "Communication",
      "Critical Thinking",
      "Problem Solving"
    ]
  },
  {
    "job": "Risk Management Specialist",
    "requiredSkills": [
      "Enterprise Risk Management",
      "Operational Risk",
      "Market Risk",
      "Credit Risk",
      "Basel Norms",
      "Regulatory Compliance",
      "Risk Assessment Tools",
      "Data Analysis",
      "Reporting",
      "Excel",
      "Communication"
    ]
  },
  {
    "job": "Treasury Manager",
    "requiredSkills": [
      "Cash Management",
      "Liquidity Management",
      "Foreign Exchange",
      "Hedging",
      "Risk Management",
      "Financial Reporting",
      "Forecasting",
      "ERP Tools",
      "Analytical Skills",
      "Communication"
    ]
  },
  {
    "job": "FinTech Analyst",
    "requiredSkills": [
      "Blockchain Basics",
      "Cryptocurrency",
      "Payment Systems",
      "Digital Banking",
      "Data Analysis",
      "SQL",
      "Python",
      "Regulatory Compliance",
      "Risk Assessment",
      "Innovation",
      "Communication"
    ]
  },
  {
    "job": "Corporate Strategy Analyst",
    "requiredSkills": [
      "Business Strategy",
      "Market Research",
      "Competitive Analysis",
      "Data Analysis (Excel",
      "SQL)",
      "Financial Modelling",
      "Presentation Skills",
      "Communication",
      "Critical Thinking",
      "Problem Solving"
    ]
  },
  {
    "job": "Auditor (Specialized)",
    "requiredSkills": [
      "Internal Audit",
      "External Audit",
      "Risk Assessment",
      "ISO/IFRS Compliance",
      "Tax Audits",
      "Forensic Auditing",
      "Accounting Software (SAP",
      "Tally)",
      "Data Analysis",
      "Documentation",
      "Communication"
    ]
  },
  {
    "job": "E-commerce Operations Manager",
    "requiredSkills": [
      "Online Store Management",
      "Product Listing",
      "Inventory Management",
      "Order Fulfillment",
      "Digital Marketing Coordination",
      "Analytics Tools",
      "SEO",
      "Customer Service",
      "Communication",
      "Problem Solving"
    ]
  },
  {
    "job": "Tax Manager (Advanced)",
    "requiredSkills": [
      "Direct Tax",
      "Indirect Tax (GST",
      "VAT)",
      "International Taxation",
      "Transfer Pricing",
      "Tax Planning",
      "Tax Compliance",
      "Accounting Software (Tally",
      "SAP)",
      "Analytical Skills",
      "Communication",
      "Regulatory Knowledge"
    ]
  },
  {
    "job": "Actuarial Analyst",
    "requiredSkills": [
      "Probability & Statistics",
      "Risk Assessment",
      "Life/Health/General Insurance",
      "Financial Modelling",
      "Excel",
      "R/Python",
      "Data Analysis",
      "Regulatory Knowledge",
      "Communication",
      "Problem Solving"
    ]
  },
  {
    "job": "Software Developer",
    "requiredSkills": [
      "Java",
      "Python",
      "C++",
      "C#",
      "JavaScript",
      "TypeScript",
      "React",
      "Angular",
      "Node.js",
      "Spring Boot",
      "Django",
      "REST APIs",
      "GraphQL",
      "Git",
      "GitHub",
      "Data Structures",
      "Algorithms",
      "OOP",
      "Design Patterns",
      "Debugging",
      "Unit Testing",
      "Agile",
      "Scrum",
      "Problem Solving",
      "Communication"
    ]
  },
  {
    "job": "Web Developer",
    "requiredSkills": [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
      "Angular",
      "Vue.js",
      "Node.js",
      "Express.js",
      "PHP",
      "Laravel",
      "Django",
      "REST APIs",
      "GraphQL",
      "Responsive Design",
      "Bootstrap",
      "Tailwind",
      "Git",
      "GitHub",
      "Testing",
      "Cross-browser Compatibility",
      "SEO Basics",
      "Web Security",
      "Problem Solving"
    ]
  },
  {
    "job": "Data Scientist",
    "requiredSkills": [
      "Python",
      "R",
      "SQL",
      "Pandas",
      "NumPy",
      "SciPy",
      "Scikit-learn",
      "TensorFlow",
      "PyTorch",
      "Keras",
      "Statistics",
      "Probability",
      "Machine Learning",
      "Deep Learning",
      "NLP",
      "Computer Vision",
      "Data Cleaning",
      "Data Visualization (Matplotlib",
      "Seaborn",
      "Tableau",
      "Power BI",
      "Big Data (Hadoop",
      "Spark)",
      "Cloud (AWS",
      "GCP",
      "Azure)",
      "Communication"
    ]
  },
  {
    "job": "Data Analyst",
    "requiredSkills": [
      "SQL",
      "Excel",
      "Python",
      "Pandas",
      "NumPy",
      "Data Cleaning",
      "Data Visualization",
      "Tableau",
      "Power BI",
      "Statistics",
      "Probability",
      "Hypothesis Testing",
      "Reporting",
      "Business Intelligence",
      "Communication",
      "Problem Solving",
      "Critical Thinking"
    ]
  },
  {
    "job": "DevOps Engineer",
    "requiredSkills": [
      "Linux",
      "Bash",
      "Shell Scripting",
      "Git",
      "Docker",
      "Kubernetes",
      "Jenkins",
      "CI/CD",
      "Terraform",
      "Ansible",
      "Puppet",
      "Chef",
      "Monitoring Tools (Prometheus",
      "Grafana)",
      "Cloud (AWS",
      "GCP",
      "Azure)",
      "Networking Basics",
      "Security",
      "Automation",
      "Problem Solving",
      "Collaboration"
    ]
  },
  {
    "job": "Cloud Engineer",
    "requiredSkills": [
      "AWS",
      "Azure",
      "GCP",
      "Linux",
      "Networking",
      "Docker",
      "Kubernetes",
      "Terraform",
      "Ansible",
      "Cloud Security",
      "Identity & Access Management (IAM)",
      "Serverless Computing",
      "Cloud Storage",
      "Load Balancing",
      "Auto Scaling",
      "Monitoring",
      "Troubleshooting",
      "Communication"
    ]
  },
  {
    "job": "AI / ML Engineer",
    "requiredSkills": [
      "Python",
      "R",
      "TensorFlow",
      "PyTorch",
      "Keras",
      "Scikit-learn",
      "Deep Learning",
      "NLP",
      "Computer Vision",
      "Transformers",
      "LLMs",
      "Reinforcement Learning",
      "Data Preprocessing",
      "Model Deployment",
      "MLOps",
      "Cloud (AWS Sagemaker",
      "GCP AI",
      "Azure ML)",
      "Git",
      "APIs",
      "Problem Solving",
      "Math (Linear Algebra",
      "Calculus",
      "Probability",
      "Statistics)"
    ]
  },
  {
    "job": "Cybersecurity Engineer",
    "requiredSkills": [
      "Networking",
      "Firewalls",
      "IDS/IPS",
      "SIEM Tools",
      "Penetration Testing",
      "Ethical Hacking",
      "Cryptography",
      "Security Protocols",
      "OWASP",
      "Vulnerability Assessment",
      "Cloud Security",
      "Endpoint Security",
      "Incident Response",
      "Forensics",
      "Risk Management",
      "Compliance (ISO",
      "GDPR",
      "HIPAA)",
      "Linux",
      "Scripting (Python",
      "Bash)",
      "Communication"
    ]
  },
  {
    "job": "UI/UX Designer",
    "requiredSkills": [
      "UI Design",
      "UX Design",
      "Wireframing",
      "Prototyping",
      "Figma",
      "Adobe XD",
      "Sketch",
      "InVision",
      "Design Systems",
      "Usability Testing",
      "Human-Computer Interaction",
      "Accessibility",
      "Responsive Design",
      "HTML",
      "CSS",
      "Collaboration",
      "Creativity",
      "Communication"
    ]
  },
  {
    "job": "Full Stack Developer",
    "requiredSkills": [
      "JavaScript",
      "TypeScript",
      "React",
      "Angular",
      "Vue.js",
      "Node.js",
      "Express.js",
      "MongoDB",
      "SQL",
      "GraphQL",
      "REST APIs",
      "HTML",
      "CSS",
      "Git",
      "Docker",
      "Kubernetes",
      "CI/CD",
      "Testing",
      "Design Patterns",
      "Problem Solving",
      "Agile",
      "Communication"
    ]
  },
  {
    "job": "Mobile App Developer",
    "requiredSkills": [
      "Java",
      "Kotlin",
      "Swift",
      "Objective-C",
      "React Native",
      "Flutter",
      "Dart",
      "iOS SDK",
      "Android SDK",
      "REST APIs",
      "GraphQL",
      "Firebase",
      "Git",
      "Testing",
      "UI/UX",
      "Deployment (App Store",
      "Play Store)",
      "Debugging",
      "Agile",
      "Communication"
    ]
  },
  {
    "job": "Game Developer",
    "requiredSkills": [
      "C++",
      "C#",
      "Unity",
      "Unreal Engine",
      "3D Modeling Basics",
      "Graphics Programming",
      "OpenGL",
      "DirectX",
      "Physics Engines",
      "AI for Games",
      "Animation",
      "Storyboarding",
      "Mathematics (Linear Algebra",
      "Geometry)",
      "Problem Solving",
      "Creativity",
      "Collaboration"
    ]
  },
  {
    "job": "Business Analyst (IT)",
    "requiredSkills": [
      "Requirements Gathering",
      "UML",
      "Use Cases",
      "SQL",
      "Excel",
      "Data Analysis",
      "Reporting",
      "Documentation",
      "Agile",
      "Scrum",
      "Communication",
      "Stakeholder Management",
      "Critical Thinking",
      "Problem Solving"
    ]
  },
  {
    "job": "Network Engineer",
    "requiredSkills": [
      "Networking Protocols (TCP/IP",
      "UDP",
      "DNS",
      "DHCP)",
      "Routing",
      "Switching",
      "Firewalls",
      "VPN",
      "Network Security",
      "Cisco",
      "Juniper",
      "Wireshark",
      "Network Troubleshooting",
      "Load Balancing",
      "Cloud Networking",
      "SDN",
      "VoIP",
      "Monitoring Tools",
      "Communication"
    ]
  }
];
