
"use client"

import { useEffect, useState, useTransition } from "react"
import { createLearningRoadmap } from "./actions"
import type { LearningRoadmapOutput } from "@/ai/flows/daily-learning"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card"
import { useToast } from "@/hooks/use-toast"
import { Loader2, ArrowRight, Book, AlertTriangle, Target, Folder, ChevronRight, Youtube, CheckCircle } from "lucide-react"
import Link from "next/link"
import { Badge } from "@/components/ui/badge"
import { Progress } from "@/components/ui/progress"

type StoredAnalysis = {
    desiredRole: string;
    userSkills: string[];
    missingSkills: string[];
    roadmap?: LearningRoadmapOutput['roadmap'];
}

type ProgressTracker = {
    [roleSlug: string]: {
        [courseSlug: string]: {
            completedSteps: string[];
            quizPassed?: boolean;
        }
    }
}

const slugify = (text: string) => {
  if (!text) return '';
  return text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)+/g, '');
};

const FallbackCard = ({ skill }: { skill: string }) => (
    <Card className="bg-muted/30 border-dashed">
        <CardHeader>
            <CardTitle className="font-headline text-lg text-muted-foreground">No Specific Steps Generated</CardTitle>
        </CardHeader>
        <CardContent>
            <p className="text-muted-foreground mb-4">
                While no specific steps were generated by the AI for "{skill}", you can start exploring on your own.
            </p>
        </CardContent>
        <CardFooter>
            <Button variant="outline" size="sm" asChild>
                <a href={`https://www.youtube.com/results?search_query=${encodeURIComponent(skill + ' tutorial')}`} target="_blank" rel="noopener noreferrer">
                    <Youtube className="mr-2 h-4 w-4 text-red-500" />
                    Search for "{skill}" on YouTube
                </a>
            </Button>
        </CardFooter>
    </Card>
);

export function LearningPlan() {
  const { toast } = useToast()
  const [isPending, startTransition] = useTransition()
  const [error, setError] = useState<string | null>(null);
  const [analysis, setAnalysis] = useState<StoredAnalysis | null>(null);
  const [isLoading, setIsLoading] = useState(true);
  const [roadmap, setRoadmap] = useState<LearningRoadmapOutput['roadmap'] | null>(null);
  const [progress, setProgress] = useState<ProgressTracker>({});

  useEffect(() => {
    try {
      const desiredRole = localStorage.getItem('desiredRole');
      const userSkills = localStorage.getItem('userSkills');
      const missingSkills = localStorage.getItem('missingSkills');
      const storedRoadmap = localStorage.getItem('learningRoadmap');
      
      if (desiredRole && userSkills && missingSkills) {
        const parsedAnalysis: StoredAnalysis = {
          desiredRole,
          userSkills: JSON.parse(userSkills),
          missingSkills: JSON.parse(missingSkills),
        };
        if(storedRoadmap) {
            const parsedRoadmap = JSON.parse(storedRoadmap);
            parsedAnalysis.roadmap = parsedRoadmap;
            setRoadmap(parsedRoadmap);
        }
        setAnalysis(parsedAnalysis);
      }
      
      const storedProgress = localStorage.getItem('learningProgress');
      if(storedProgress) {
        setProgress(JSON.parse(storedProgress));
      }

    } catch (e) {
      console.error("Failed to load data from local storage", e);
      setError("Could not load your learning data from your browser.");
    } finally {
        setIsLoading(false);
    }

    const handleStorageChange = () => {
        const storedProgress = localStorage.getItem('learningProgress');
        if(storedProgress) {
            setProgress(JSON.parse(storedProgress));
        }
    }
    window.addEventListener('storage', handleStorageChange);
    return () => window.removeEventListener('storage', handleStorageChange);

  }, []);

  const handleGeneratePlan = () => {
    if (!analysis) return;
    if (analysis.missingSkills.length === 0) {
      toast({
        title: "No Gaps to Fill!",
        description: "You already have all the required skills for this role.",
      });
      return;
    }

    startTransition(async () => {
      setError(null);
      try {
        const result = await createLearningRoadmap({
          userSkills: analysis.userSkills,
          desiredRole: analysis.desiredRole,
          missingSkills: analysis.missingSkills,
        });
        setRoadmap(result.roadmap);
        localStorage.setItem('learningRoadmap', JSON.stringify(result.roadmap));
        toast({
          title: "Roadmap Generated!",
          description: "Your personalized learning plan is ready.",
        });
      } catch (e: any) {
        setError(e.message);
        toast({
          title: "Error Generating Roadmap",
          description: e.message,
          variant: "destructive",
        });
      }
    });
  };
  
  if (isLoading) {
    return (
        <Card className="flex flex-col items-center justify-center p-10 text-center min-h-[400px]">
            <Loader2 className="mx-auto h-12 w-12 animate-spin text-primary mb-4" />
            <p className="text-lg text-muted-foreground">Loading Your Learning Data...</p>
        </Card>
    );
  }
  
  if (!analysis) {
      return (
        <Card className="text-center">
            <CardHeader>
                <div className="mx-auto bg-primary/10 p-4 rounded-full w-fit">
                    <Target className="h-10 w-10 text-primary" />
                </div>
                <CardTitle className="font-headline mt-4 text-2xl">
                    Start with Skill Gap Analysis
                </CardTitle>
                <CardDescription className="text-base">
                    To get a personalized learning roadmap, you first need to identify your skill gaps.
                </CardDescription>
            </CardHeader>
            <CardContent>
                <p className="text-muted-foreground mb-6 max-w-md mx-auto">
                    Head over to the Skill Gap Analyzer, tell us about your goals, and we'll create a tailored plan for you to follow.
                </p>
                <Button asChild>
                    <Link href="/dashboard/skill-gap">
                        Analyze My Skills <ArrowRight className="ml-2"/>
                    </Link>
                </Button>
            </CardContent>
        </Card>
      )
  }

  const currentRoadmap = roadmap || analysis.roadmap;
  const roleSlug = slugify(analysis.desiredRole);
  const roleProgress = progress[roleSlug] || {};


  return (
    <>
      <div className="space-y-8">
        <Card>
            <CardHeader>
                <CardTitle className="font-headline text-2xl">Your Learning Focus</CardTitle>
                <CardDescription>This roadmap is designed to bridge the skill gaps for your goal of becoming a <strong>{analysis.desiredRole}</strong>.</CardDescription>
            </CardHeader>
            <CardContent className="flex flex-wrap gap-2">
                {analysis.missingSkills.length > 0 ? analysis.missingSkills.map(skill => (
                    <Badge key={skill} variant="secondary" className="text-base py-1 px-3">
                        {skill}
                    </Badge>
                )) : <p className="text-muted-foreground">No skill gaps identified. You're all set!</p>}
            </CardContent>
        </Card>

        {currentRoadmap ? (
          <div className="space-y-4">
            <h2 className="text-3xl font-bold font-headline text-center">Your Personalized Learning Roadmap</h2>
            {analysis.missingSkills.map(skill => {
              const skillSlug = slugify(skill);
              const skillSteps = currentRoadmap.filter(step => {
                  const stepNameLower = step.stepName.toLowerCase();
                  const courseLower = step.recommendedCourse.toLowerCase();
                  const skillLower = skill.toLowerCase();
                  return stepNameLower.includes(skillLower) || courseLower.includes(skillLower);
              });

              const completedCount = roleProgress[skillSlug]?.completedSteps?.length || 0;
              const totalCount = skillSteps.length > 0 ? skillSteps.length : 1; // Avoid division by zero
              const progressPercentage = totalCount > 0 ? (completedCount / totalCount) * 100 : 0;
              const isMastered = roleProgress[skillSlug]?.quizPassed || false;

              return (
              <Card key={skill} className="hover:border-primary/50 transition-colors">
                 <Link href={`/dashboard/daily-learning/course/${skillSlug}`}>
                    <div className="p-6">
                        <div className="flex justify-between items-start">
                            <div>
                                <div className="flex items-center gap-3">
                                    <Folder className="h-6 w-6 text-primary" />
                                    <span className="text-xl font-headline font-semibold">{skill}</span>
                                    {isMastered && <Badge className="bg-green-500 hover:bg-green-600 text-white"><CheckCircle className="mr-1 h-4 w-4"/>Mastered</Badge>}
                                </div>
                                <p className="text-muted-foreground mt-2">
                                    {skillSteps.length > 0 ? `${skillSteps.length} learning resources available.` : `Explore resources for ${skill}.`}
                                </p>
                            </div>
                            <ChevronRight className="h-6 w-6 text-muted-foreground mt-1" />
                        </div>
                        {skillSteps.length > 0 && (
                            <div className="mt-4">
                                <div className="flex justify-between text-sm text-muted-foreground mb-1">
                                    <span>Progress</span>
                                    <span>{completedCount}/{totalCount} completed</span>
                                </div>
                                <Progress value={progressPercentage} className="h-2" />
                            </div>
                        )}
                    </div>
                 </Link>
              </Card>
            )})}
            <div className="text-center pt-4">
                <Button onClick={handleGeneratePlan} disabled={isPending}>
                    {isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                    Regenerate Roadmap
                </Button>
            </div>
          </div>
        ) : (
           <Card className="text-center">
            <CardHeader>
                 <div className="mx-auto bg-primary/10 p-4 rounded-full w-fit">
                    <Book className="h-10 w-10 text-primary" />
                </div>
                <CardTitle className="font-headline mt-4 text-2xl">
                    Generate Your Learning Roadmap
                </CardTitle>
                <CardDescription className="text-base">
                    You have identified your skill gaps. Now, let our AI create a step-by-step learning plan for you.
                </CardDescription>
            </CardHeader>
            <CardContent>
                <Button onClick={handleGeneratePlan} disabled={isPending}>
                    {isPending ? (
                        <><Loader2 className="mr-2 h-4 w-4 animate-spin" /> Building Your Plan...</>
                    ) : (
                        <>Generate My Roadmap</>
                    )}
                </Button>
            </CardContent>
           </Card>
        )}

        {error && (
              <Card className="flex flex-col items-center justify-center p-10 text-center min-h-[200px]">
                  <AlertTriangle className="mx-auto h-12 w-12 text-destructive mb-4" />
                  <p className="text-destructive font-semibold text-xl">Oops! Something went wrong.</p>
                  <p className="text-muted-foreground mt-2">{error}</p>
                  <Button onClick={handleGeneratePlan} className="mt-6" disabled={isPending}>
                    {isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
                    Retry
                  </Button>
              </Card>
        )}
      </div>
    </>
  )
}
